package life.mastar.community.community.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commusers.ID
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commusers.ACCOUNT_ID
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commusers.NAME
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commusers.TOKEN
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commusers.GMT_CREATE
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commusers.GMT_MODIFY
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    private Long gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commusers.AVATAR_URL
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commusers.ID
     *
     * @return the value of commusers.ID
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commusers.ID
     *
     * @param id the value for commusers.ID
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commusers.ACCOUNT_ID
     *
     * @return the value of commusers.ACCOUNT_ID
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commusers.ACCOUNT_ID
     *
     * @param accountId the value for commusers.ACCOUNT_ID
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commusers.NAME
     *
     * @return the value of commusers.NAME
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commusers.NAME
     *
     * @param name the value for commusers.NAME
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commusers.TOKEN
     *
     * @return the value of commusers.TOKEN
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commusers.TOKEN
     *
     * @param token the value for commusers.TOKEN
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commusers.GMT_CREATE
     *
     * @return the value of commusers.GMT_CREATE
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commusers.GMT_CREATE
     *
     * @param gmtCreate the value for commusers.GMT_CREATE
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commusers.GMT_MODIFY
     *
     * @return the value of commusers.GMT_MODIFY
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public Long getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commusers.GMT_MODIFY
     *
     * @param gmtModify the value for commusers.GMT_MODIFY
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public void setGmtModify(Long gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commusers.AVATAR_URL
     *
     * @return the value of commusers.AVATAR_URL
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commusers.AVATAR_URL
     *
     * @param avatarUrl the value for commusers.AVATAR_URL
     *
     * @mbg.generated Wed Feb 19 12:03:41 CST 2020
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}